###使用默认配置就可以了,不需要修改###
#server:
#    port: 8080
#    sevlet: 
#        context-path: /


springrain: 
    session:    ###session和cache可以公用这个参数.
        timeout: 1800000
        
        
#logging: 
#     level: 
#         org: INFO ### 配置spring web日志级别###
 
spring: 
    datasource: 
        url: jdbc:mysql://127.0.0.1:3306/springrain?characterEncoding=utf8&useUnicode=true&useSSL=false
        username: root
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        default-transaction-isolation: ISOLATION_READ_UNCOMMITTED


###代码实现:org.springrain.config.SpringMVCConfig.addResourceHandlers(ResourceHandlerRegistry)###
#    resources: 
#          static-locations: /images/,/img/,/js/,/css/,/layui/,/upload/,/u/
          
    mvc: 
        ignore-default-model-on-redirect: false ###在重定向时是否忽略默认model的内容，默认为true###
        
    aop: 
        proxy-target-class: false
        
        
        
        
#    redis: 
#        host: 127.0.0.1
#        port: 6379
#        timeout: 1800000
#        pool: 
#            max-active: 1024
#            min-idle: 200



    http: 
        encoding: 
            charset: UTF-8
            enabled: true
            force: true
            
    openoffice: 
        home: D:/Program Files (x86)/OpenOffice 4/program/soffice.exe
        host: 127.0.0.1
        port: 8100
        
        
###actuator的默认路径/actuator/ 开头,已经在shiro配置,只有system有权限###        
management: 
    endpoints: 
        web: 
            exposure: 
                include: '*'